apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: jeetkansagra07/ultimate-cicd:6b0370480c36e4e6ee9bd47b02ca048c4546a3bf
        ports:
        - containerPort: 8080