apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: jeetkansagra07/ultimate-cicd:dbadb5d1c18245fe23d4ac6435f6631f5d124816
        ports:
        - containerPort: 8080